Typed library
metarhia/metavm pull request #29
Opened 2020-10-25 14:51 UTC by razenization

Hello, please review the typings I wrote and approve if valid.

2020-10-25 20:51 UTC, tshemsedinov requested changes
- Please move all typings to `/types`, see example: https://github.com/metarhia/metatests
- Add https://www.npmjs.com/package/@types/node to dependencies for builtin node.js libraries, for example `BaseOptions`
- Use interfaces in most cases

2020-10-25 20:51 UTC, tshemsedinov commented on lib/loader.d.ts
> +export declare const readScript: (
```suggestion
export declare {
  function readScript(
```

2020-10-25 20:51 UTC, tshemsedinov commented on lib/vm.d.ts
> +};
We don't need to specify this certain list

2020-10-25 20:51 UTC, tshemsedinov commented on lib/vm.d.ts
> +type VMContextLibDOMTypes = {
Use interfaces instead of types

2020-10-25 20:51 UTC, tshemsedinov commented on lib/vm.d.ts
> +    options?: vm.ScriptOptions & { context: vm.Context }
Need new interface for options

2020-10-25 20:51 UTC, tshemsedinov commented on lib/vm.d.ts
> +) => MetaScript;
```suggestion
function createScript(name: string, src: string, options?: MetaOptions): MetaScript;
```

2020-10-26 15:20 UTC, razenization commented
Tried replacing the parts you emphasized on. May I ask why would it be necessary to stick with interfaces? I was pretty concerned that the "type" structure is more powerful until now.
Also, I didn't manage to get proper use of node types installation, hence still had to require the options interface.
Thanks for reviewing my code.

2026-06-27 01:30 UTC, closed without merging