Require context bounded
metarhia/metavm pull request #56
Opened 2021-04-18 09:51 UTC by AliusDieMorietur

Fix: #34 
Now when context created require bounding to this context using closure, when `require` called in vm it gets value from context with `Reflect`  if it exists.

- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)

2021-04-20 21:54 UTC, tshemsedinov requested changes
Need more tests for nested modules

2021-04-20 22:49 UTC, AliusDieMorietur commented
`Require` should have ability to work with modules in side files and replace require in there scopre and be binded to context we declared? Something like: `require('../module1.js')` module1.js: `const fs = require('fs'); `

2021-04-20 23:38 UTC, tshemsedinov commented
Yes, module1 -> require(fs) and even module1 -> require(module2) -> module2 -> require(fs)

2021-04-29 20:43 UTC, AliusDieMorietur commented
Due to misclick lost conrtol on old repo, so this PR will be closed and created new #58

2021-04-29 20:43 UTC, closed without merging